main:
	g++ main.cpp Task.cpp TodoList.cpp ProgramMenu.cpp -o program.x
	g++ newtestclass.cpp newtestrunner.cpp Task.cpp -o test1.x -lcppunit
	g++ newtestclass1.cpp newtestrunner1.cpp Task.cpp TodoList.cpp -o test2.x -lcppunit
	
run:
	./program.x
